[font]
size = 11.0

[font.bold]
family = "Inconsolata LGC Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Inconsolata LGC Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Inconsolata LGC Nerd Font"
style = "Italic"

[font.normal]
family = "Inconsolata LGC Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0
